// mentalHealthWords.js

const mentalHealthWords = [
    "Anxiety",
    "Depression",
    "Therapy",
    "Counseling",
    "Wellness",
    "Stress",
    "Mindfulness",
    "Resilience",
    "Coping",
    "Psychologist",
    "Psychiatrist",
    "SelfCare",
    "Meditation",
    "Emotional",
    "Support",
    "WellBeing",
    "Bipolar",
    "Trauma",
    "Recovery",
    "Addiction",
    "Suicidal",
    "Psychiatric",
    "Healing",
    "SelfEsteem",
    "Schizophrenia",
    "Psychotherapy",
    "Stigma",
    "Empathy",
    "Medication",
    "Awareness",
    "MentalIllness",
    "Positive",
    "CopingMechanisms",
    "Mindset",
    "InnerPeace",
    "Therapist",
    "SocialSupport",
    "Neurotransmitters",
    "Insomnia",
    "Happiness",
    "Acceptance",
    "PTSD",
    "EmotionalIntelligence",
    "SelfReflection",
    "CopingStrategies",
    "Counseling",
    "MindBodyConnection",
    "PersonalGrowth",
    "CBT",
    "Sad" ,
    "depressed"// Example acronym for Cognitive-Behavioral Therapy
  ];
  
export default mentalHealthWords;
  